### ISSUE TITLE
Using SLM Lab

### ISSUE THREAD

**Issue by amirmahdiKhosravi** [hardmaru/slimevolleygym#15]
Hi,

Is there any way to use SLM lab for this environment?

**Comment by hardmaru** [comment]
Hi!

I haven't tried SLM lab, but I've tried to use other RL frameworks (such as Chainer RL) on the env and it worked (since it's just a Gym env)

Maybe you can check out the Chainer RL example, and it might help with your SLM lab setup?

Chainer RL using slimevolley: https://github.com/hardmaru/RainbowSlimeVolley

Cheers
