### ISSUE TITLE
The ball can go through the net

### ISSUE THREAD

**Issue by muupan** [hardmaru/slimevolleygym#8]
First of all, thank you so much for sharing the nice env and the baselines! I'm happy to see that ChainerRL is chosen for the Rainbow baseline.

Regarding the issue described in the title, please look at the attached animation.
 
![ballgothroughnet](https://user-images.githubusercontent.com/815970/86511877-1059fb80-be38-11ea-9bc2-b603ca3c5c36.gif)

I'm not sure if the issue needs to be fixed because it rarely happens (at least in my experiences so far with this env). However, it could possibly be exploited by some clever agent. That agent would be undefeatable.

**Comment by hardmaru** [comment]
Hi @muupan, I'm aware of this issue (from the game's original design, to cut some corners), but I haven't been able to train an agent to find an exploit for it. If a clever agent manages to exploit it (and get an unreasonably high average score against other agents), let's acknowledge it on the page / leaderboard first since it'll be a really fun example to showcase, and then fix it (with a version bump).

**Comment by muupan** [comment]
Sounds like a plan. Should this issue be closed for now or kept open until it is fixed? Either is fine for me.

**Comment by hardmaru** [comment]
Sounds good- let’s close for now (and maybe revisit again)!
